"""create appointments table

Revision ID: 7c55e96cd3c2
Revises: ed6325972492
Create Date: 2026-08-08 23:19:58.001840+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c55e96cd3c2'
down_revision: str | None = 'ed6325972492'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    op.create_table('appointments',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointmentstatus', native_enum=False), server_default='requested', nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_late', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('ix_appointments_patient', ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index('ix_appointments_patient')
        batch_op.drop_index('ix_appointments_doctor')

    op.drop_table('appointments')
    # ### end Alembic commands ###
