"""add encounter sensitivity and consent flags

Revision ID: 69a027b6d00b
Revises: 373f7898b52e
Create Date: 2026-08-09 16:08:24.932013+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a027b6d00b'
down_revision: str | None = '373f7898b52e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    # NOTE: a spurious vitals.flags server-default "diff" (a SQLite representation
    # quirk, not a real change) was removed during review; this migration only
    # adds the two consent-gating columns.
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensitive', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('consent_shared', sa.Boolean(), server_default='0', nullable=False))


def downgrade() -> None:
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_column('consent_shared')
        batch_op.drop_column('sensitive')
