"""create prescription domain tables

Revision ID: f8d94a046c95
Revises: 69a027b6d00b
Create Date: 2026-08-09 16:19:50.662500+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d94a046c95'
down_revision: str | None = '69a027b6d00b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    op.create_table('medications',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('drug_class', sa.String(length=64), nullable=True),
    sa.Column('is_controlled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_drug_class'), ['drug_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_name'), ['name'], unique=True)

    op.create_table('allergies',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('substance', sa.String(length=128), nullable=False),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergies_patient_id'), ['patient_id'], unique=False)

    op.create_table('drug_interactions',
    sa.Column('medication_a_id', sa.Integer(), nullable=False),
    sa.Column('medication_b_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_a_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_b_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_a_id', 'medication_b_id', name='uq_interaction_pair')
    )
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.create_index('ix_drug_interactions_a', ['medication_a_id'], unique=False)
        batch_op.create_index('ix_drug_interactions_b', ['medication_b_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescriber_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dose', sa.String(length=128), nullable=False),
    sa.Column('refills', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescriber_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_encounter_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_drug_interactions_b')
        batch_op.drop_index('ix_drug_interactions_a')

    op.drop_table('drug_interactions')
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergies_patient_id'))

    op.drop_table('allergies')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_name'))
        batch_op.drop_index(batch_op.f('ix_medications_drug_class'))

    op.drop_table('medications')
    # ### end Alembic commands ###
