"""create encounters and addenda tables

Revision ID: 79326e773cf9
Revises: 7c55e96cd3c2
Create Date: 2026-08-09 00:51:08.914736+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79326e773cf9'
down_revision: str | None = '7c55e96cd3c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    op.create_table('addenda',
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addenda', schema=None) as batch_op:
        batch_op.create_index('ix_addenda_target', ['target_type', 'target_id'], unique=False)

    op.create_table('encounters',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index('ix_encounters_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('ix_encounters_patient', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### auto-generated by Alembic; reviewed (DESIGN §8) ###
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index('ix_encounters_patient')
        batch_op.drop_index('ix_encounters_doctor')

    op.drop_table('encounters')
    with op.batch_alter_table('addenda', schema=None) as batch_op:
        batch_op.drop_index('ix_addenda_target')

    op.drop_table('addenda')
    # ### end Alembic commands ###
